-- +goose Up
CREATE TABLE tag 
(
    id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    utime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO tag (name) VALUES("go");
INSERT INTO tag (name) VALUES("mysql");

CREATE TABLE article_tag 
(
    id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    tag_id int(10) UNSIGNED NOT NULL,
    article_id int(10) UNSIGNED NOT NULL,
    ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    utime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT article_tag_fk_tag FOREIGN KEY(tag_id) REFERENCES tag(id),
    CONSTRAINT article_tag_fk_article FOREIGN KEY(article_id) REFERENCES article(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- +goose Down
DELETE FROM tag;
DROP TABLE tag;

DROP TABLE article_tag;
